//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsrsPowerInterace.AsrsSvc {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WCFPowerSys")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AsrsSvc.IAsrsPowerSvc")]
    public interface IAsrsPowerSvc {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAsrsPowerSvc/GetData", ReplyAction="http://tempuri.org/IAsrsPowerSvc/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAsrsPowerSvc/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IAsrsPowerSvc/GetDataUsingDataContractResponse")]
        AsrsPowerInterace.AsrsSvc.CompositeType GetDataUsingDataContract(AsrsPowerInterace.AsrsSvc.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAsrsPowerSvc/GetInterfaceVersion", ReplyAction="http://tempuri.org/IAsrsPowerSvc/GetInterfaceVersionResponse")]
        string GetInterfaceVersion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAsrsPowerSvc/IsAsrsCellReady", ReplyAction="http://tempuri.org/IAsrsPowerSvc/IsAsrsCellReadyResponse")]
        bool IsAsrsCellReady(int row, int col, int layer, ref string[] barCodes, ref bool isReady, ref string reStr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAsrsPowerSvc/PowerFillOk", ReplyAction="http://tempuri.org/IAsrsPowerSvc/PowerFillOkResponse")]
        bool PowerFillOk(int row, int col, int layer, ref string reStr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAsrsPowerSvc/CommitCheckResult", ReplyAction="http://tempuri.org/IAsrsPowerSvc/CommitCheckResultResponse")]
        bool CommitCheckResult(string barcode, int checkRe, ref string reStr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAsrsPowerSvc/CellValidStatNotify", ReplyAction="http://tempuri.org/IAsrsPowerSvc/CellValidStatNotifyResponse")]
        bool CellValidStatNotify(int row, int col, int layer, bool cellValid, string reason, ref string reStr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAsrsPowerSvc/CellEmerDangerNotify", ReplyAction="http://tempuri.org/IAsrsPowerSvc/CellEmerDangerNotifyResponse")]
        bool CellEmerDangerNotify(int row, int col, int layer, string reason, ref string reStr);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAsrsPowerSvcChannel : AsrsPowerInterace.AsrsSvc.IAsrsPowerSvc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AsrsPowerSvcClient : System.ServiceModel.ClientBase<AsrsPowerInterace.AsrsSvc.IAsrsPowerSvc>, AsrsPowerInterace.AsrsSvc.IAsrsPowerSvc {
        
        public AsrsPowerSvcClient() {
        }
        
        public AsrsPowerSvcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AsrsPowerSvcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AsrsPowerSvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AsrsPowerSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public AsrsPowerInterace.AsrsSvc.CompositeType GetDataUsingDataContract(AsrsPowerInterace.AsrsSvc.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public string GetInterfaceVersion() {
            return base.Channel.GetInterfaceVersion();
        }
        
        public bool IsAsrsCellReady(int row, int col, int layer, ref string[] barCodes, ref bool isReady, ref string reStr) {
            return base.Channel.IsAsrsCellReady(row, col, layer, ref barCodes, ref isReady, ref reStr);
        }
        
        public bool PowerFillOk(int row, int col, int layer, ref string reStr) {
            return base.Channel.PowerFillOk(row, col, layer, ref reStr);
        }
        
        public bool CommitCheckResult(string barcode, int checkRe, ref string reStr) {
            return base.Channel.CommitCheckResult(barcode, checkRe, ref reStr);
        }
        
        public bool CellValidStatNotify(int row, int col, int layer, bool cellValid, string reason, ref string reStr) {
            return base.Channel.CellValidStatNotify(row, col, layer, cellValid, reason, ref reStr);
        }
        
        public bool CellEmerDangerNotify(int row, int col, int layer, string reason, ref string reStr) {
            return base.Channel.CellEmerDangerNotify(row, col, layer, reason, ref reStr);
        }
    }
}
